# Generated by Django 5.2.4 on 2025-08-20 11:26

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DescriptionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranslationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="'button.read_more', 'title.home'", max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
                ('value_en', models.TextField(blank=True, null=True)),
                ('value_ru', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('bio', models.CharField(blank=True, max_length=240)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('title_en', models.CharField(max_length=255, null=True, unique=True)),
                ('title_ru', models.CharField(max_length=255, null=True, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('subtitle_en', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('small_description', models.CharField(blank=True, max_length=255)),
                ('small_description_en', models.CharField(blank=True, max_length=255, null=True)),
                ('small_description_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('body', ckeditor.fields.RichTextField()),
                ('body_en', ckeditor.fields.RichTextField(null=True)),
                ('body_ru', ckeditor.fields.RichTextField(null=True)),
                ('meta_description', models.CharField(blank=True, max_length=150)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='description_images/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='description_images/')),
                ('custom_css_class', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('number', models.PositiveIntegerField(default=0, help_text='Порядок отображения')),
                ('description_tags', models.ManyToManyField(blank=True, to='myapp.descriptiontag')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.profile')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('title_en', models.CharField(max_length=255, null=True, unique=True)),
                ('title_ru', models.CharField(max_length=255, null=True, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('subtitle_en', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField()),
                ('body_en', models.TextField(null=True)),
                ('body_ru', models.TextField(null=True)),
                ('meta_description', models.CharField(blank=True, max_length=150)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='section_images/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='section_images/')),
                ('custom_css_class', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('number', models.PositiveIntegerField(default=0, help_text='Порядок отображения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.profile')),
                ('tags', models.ManyToManyField(blank=True, to='myapp.tag')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('title_en', models.CharField(max_length=255, null=True, unique=True)),
                ('title_ru', models.CharField(max_length=255, null=True, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('subtitle_en', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('small_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('small_description_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('small_description_ru', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('body', ckeditor.fields.RichTextField()),
                ('body_en', ckeditor.fields.RichTextField(null=True)),
                ('body_ru', ckeditor.fields.RichTextField(null=True)),
                ('meta_description', models.CharField(blank=True, max_length=150)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('views', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.profile')),
                ('tags', models.ManyToManyField(blank=True, to='myapp.tag')),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='ConceptSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('title_en', models.CharField(max_length=255, null=True, unique=True)),
                ('title_ru', models.CharField(max_length=255, null=True, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('subtitle_en', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('body', ckeditor.fields.RichTextField()),
                ('body_en', ckeditor.fields.RichTextField(null=True)),
                ('body_ru', ckeditor.fields.RichTextField(null=True)),
                ('meta_description', models.CharField(blank=True, max_length=150)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='section_images/')),
                ('custom_css_class', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='section_images/')),
                ('number', models.PositiveIntegerField(default=0, help_text='Порядок отображения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.profile')),
                ('tags', models.ManyToManyField(blank=True, to='myapp.tag')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
