# Generated by Django 5.2.4 on 2026-02-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.RemoveField(
            model_name='description',
            name='description_tags',
        ),
        migrations.AddField(
            model_name='description',
            name='tags',
            field=models.ManyToManyField(blank=True, to='myapp.tag'),
        ),
        migrations.DeleteModel(
            name='ConceptSection',
        ),
        migrations.DeleteModel(
            name='DescriptionTag',
        ),
    ]
